---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directories:
      - /src/connect_handler/
      - /src/disconnect_handler/
      - /src/sendmessage_handler/
      - /src/webhook_handler/
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directories:
      - /src/webhook_handler/
    schedule:
      interval: daily
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: /modules/dynamodb/
    schedule:
      interval: daily
    open-pull-requests-limit: 10
